update CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,67 +1,72 @@
-# This is a basic workflow to help you get started with Actions
-
 name: CI
 
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events for the main branch or for release branches
+  # Runs on pushes targeting the default branch
   push:
-    branches:
-      - 'master'
-      - 'release/*'
-    tags:
-      - '*'
+    branches: ["master"]
+
+  # Runs on PRs against master.
   pull_request:
-    branches: [ master ]
+    branches:
+      - master
+
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow one concurrent deployment
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
+
 jobs:
-  Build:
+  build: 
     runs-on: ubuntu-latest
     steps:
+      - name: Install elan
+        run: |
+          set -o pipefail
+          curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
+          ./elan-init -y --default-toolchain none
+          echo "$HOME/.elan/bin" >> $GITHUB_PATH
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Download cached build
+        run: lake exe cache get
+      - name: Build SciLean
+        run: lake exe sclean --directory _out/
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+        with:
+          # Upload entire repository
+          path: '.'
 
-    - name: Install expect
-      run: sudo apt-get install -y expect
-
-    - name: Checkout
-      uses: actions/checkout@v2
-
-    - name: Setup Python
-      uses: actions/setup-python@v3
-      with:
-        python-version: 3.10.4
-
-    - name: Setup elan toolchain on this build
-      run: |
-        curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
-        chmod u+x elan-init.sh
-        ./elan-init.sh -y --default-toolchain none
-
-    - name: Set elan paths
-      run: |
-        echo "$HOME/.elan/bin" >> $GITHUB_PATH
-
-    - name: Setup mdBook
-      uses: peaceiris/actions-mdbook@v1
-      with:
-        mdbook-version: '0.4.17'
-
-    - name: Install mdbook-wordcount
-      uses: baptiste0928/cargo-install@v1
-      with:
-        crate: mdbook-wordcount
-        version: latest
-
-    - name: Build book
-      run: |
-        cd scientific-computing-lean
-        mdbook build
+  # Single deploy job since we're just deploying
+  deploy:
+    # only build on `master` branch of the actual remote, NOT on PRs.
+    # this stops PRs from attempting to deploy GH pages and failing to do so.
+    if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
 
     - name: Deploy to GitHub Pages
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./scientific-computing-lean/book
+        publish_dir: ./_out/html-multi/
 
